tls:
    options:
        default:
            minVersion: "VersionTLS12"
    stores:
        default:
            defaultCertificate:
http:
    serversTransports:
        ignorecert:
            insecureSkipVerify: true