api:
    dashboard: true

log:
    format: "json"

accessLog:
    format: "json"
    filters:
        statusCodes:
            - "400-599"

entryPoints:
    web:
        address: ":80"
        http:
            redirections:
                entryPoint:
                    to: "websecure"
                    scheme: "https"

    websecure:
        address: ":443"
        http:
            tls: {}

providers:
    docker:
        endpoint: "unix:///var/run/docker.sock"
        exposedByDefault: false
    file:
        filename: "/configurations/dynamic.yml"